### ISSUE TITLE
Small changes, minor updates

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/IMAGE-InjectTool#50]
**Is your feature request related to a problem? Please describe.**
Here are described some ideas or improvement not related to a specific issue or a problem in particular

**Additional context**
- [x] check `validation.admin`
  - check `__str__` methods
  - check plurals
  - check columns displayed
- [x] use `bumpversion` to manage versions?
- [x] disable validation links while `WAITING` - not useful we can inspect errors while waitin and we can't update or fix in this state
- [x] what to do when getting a specie not in `DictSpecie` table?
- [x] `TaskFailureMixin` should be unique and used by all tasks - issue #58
- [x] batch update doesn't update the `last_changed` colum in `Name` table
- [x] add the update submission view
- [x] country should't be added when importing data - issue #57
- [x] pinning kumbu library and fix issues with flower - ussue #6 
- [x] send mail to admin when a task fail - issue #58
- [x] use `common.helpers.send_mail_to_admins` when sending a mail to admin is needed - issue #58
- [x] configure git LFS
- [x] uploading csv file with cryoweb path should raise an exception or a more informative error
- [x] take a look to https://medium.com/@ksarthak4ever/django-and-web-security-headers-d72a9e54155e - will have a dedicated issue
- [x] solve the cookie problem with font-awesome and google-chrome - seems has been solved by font-awesome
- [x] cryoweb data with GPS coordinates will fail validation since we don't have place as a `text` - should this be fixed with geographic referencing tool?
- [x] biosample submission data tables can be deleted if the submission process went ok?
- [x] add the contact to text for missing organizations (affiliation/organizations)
- [x] filter validation by owner in admin - devel
- [x] filter biosample objects as validation object in admin - devel
- [x] use `submission.id` instead of str(submission) in task retrieval logs - devel
- [x] the `reset_submission` management command should free also `biosample.Submission` table - no, should be done by hand since there can be opened USI submissions
- [x] add views for organization objects as view for update organization information
- [x] the retrieval task could be done in parallel - will have a dedicated issue
- [x] remove text placeholder from dashboard
- [x] warn user if they delete a submission with biosample names
- [x] better error message when uploading a missing relationship during excel upload
- [x] Add last species and translations to `initializedb`
