### ISSUE TITLE
Update Biosamples data generation

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/IMAGE-InjectTool#67]
**Is your feature request related to a problem? Please describe.**
Data submitted to biosample should be updated

**Describe the solution you'd like**
Biosamples data should have the InjectTool submission id, the `same as` attribute implemented and the breed ontology should point to specie ontology if no mapping ontology is found

**Describe alternatives you've considered**
Those updates are required to manage better data submission and siupport

**Additional context**
- [x] add a key for injecttool submission id in biosample data
- [ ] model the `same as` attribute into database - moved into #70
- [ ] implement the `same as` attribute in biosample generation - moved into #70
- [ ] edit Animal/Sample views to show the `same as` attribute - moved into #70
- [ ] change CRBanim data load to handle `same as` data - moved into #70
- [x] breed ontology should point to base ontology if no mapped term is found
- [x] model the general breed relation into the database
- [x] test the new biosample data with ValidationTool - ignored for the moment

**Comment by bunop** [comment]
The `same as` is difficult to handle since I can't refer to a BioSamples accession I don't own. Moreover, the `IMAGE submission id` need to be modeled in `IMAGE-metadata` and in ValidationTool or I will have a warning everytime I do the validation

**Comment by wizardfan** [comment]
I believe that when the sample is public, you could add same as relationship to that

**Comment by bunop** [comment]
No, it's not possible

**Comment by wizardfan** [comment]
I have checked with BioSamples team who confirms that it is possible to same as any sample as long as the referenced one is public

**Comment by bunop** [comment]
I will open an issue into the mailing list

**Comment by bunop** [comment]
the *same as* relationship will be modeled in issue #70

**Comment by bunop** [comment]
I removed the `IMAGE submission id` attribute to suppress valdiation warnings and pass validation tests. I need to revert  commit `9b1833b`  once `IMAGE-ValidatIonTool` and `IMAGE-metadata` will be updated

**Comment by wizardfan** [comment]
It is common to convert/remove fields before validation, for example
https://github.com/FAANG/dcc-portal-backend/blob/master/scripts/validate_analysis_record.py
two class variables define which columns to be renamed and removed respectively as they have different names and do not exist in the ruleset.
